config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get      "/homepage",           to: "entretenimento#index",      as: :index
  get      "/filmes",             to: "entretenimento#movies",     as: :movies
  get      "/series",             to: "entretenimento#tv_shows",   as: :tv_shows
  get      "/musicas",            to: "entretenimento#songs",      as: :songs
  get      "/personagens",        to: "entretenimento#characters", as: :characters
  get      "/livros",             to: "entretenimento#books",      as: :books
  get      "/programas_de_radio", to: "entretenimento#podcasts",   as: :podcasts
  post     "/cadastrando",        to: "user#cadastro",             as: :cadastro
  get      "/registros",          to: "user#lista",                as: :lista
  get      "/show/:id",           to: "user#show",                 as: :show
  get      "/edit/:id/edit",      to: "user#edit",                 as: :edit
  patch    "/update/:id",         to: "user#update",               as: :update
  delete   "/destroy/:id",        to: "user#destroy",              as: :destroy


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  attr_accessor :nome, :nota
  def initialize (nome, nota)
    @nome = nome
    @nota = nota
  end
  def adicionar_nota (nova_nota)
    @nota << nova_nota
  end
  # def soma_nota
  #   total = 0
  #   @notas.each do |n|
  #     total += n
  #   end
  #   puts total
  # end
  def soma_nota
    puts @nota.sum
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entretenimento_controller.rb
class EntretenimentoController < ApplicationController

  def index

  end

  def movies
    @movies = []
    (1..8).each do
      title = Faker::Movie.title
      quote = Faker::Movie.quote
      @movies << {title: title, quote:quote}
    end
  end

  def tv_shows
    @tv_shows = []
    (1..4).each do
      coisas_estranhas = Faker::TvShows::StrangerThings.quote
      bob_esponja = Faker::TvShows::Spongebob.quote
      @tv_shows << {coisas_estranhas: coisas_estranhas, bob_esponja: bob_esponja}
    end
  end

  def songs
    @songs = []
    (1..8).each do
      genre = Faker::Music.genre
      band = Faker::Music.band
      @songs << {genre: genre, band: band}
    end
  end

  def characters
    @characters = []
    (1..4).each do
      bigbang = Faker::TvShows::BigBangTheory.character
      supernatural = Faker::TvShows::Supernatural.character
      game_of_thrones = Faker::TvShows::GameOfThrones.character
      @characters << {bigbang: bigbang, supernatural: supernatural, game_of_thrones: game_of_thrones}
    end
  end

  def books
    @books = []
    (1..8).each do
      genre = Faker::Book.genre
      author = Faker::Book.author
      title = Faker::Book.title
      @books << {genre: genre, author: author, title: title}
    end
  end

  def podcasts
    @podcasts = []
    (1..8).each do
      game = Faker::Game.title
      genre = Faker::Game.genre
      @podcasts << {game: game, genre: genre}
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  attr_accessor :name, :idade
  def lista
    @users = User.all
  end

  def cadastro
    User.connection
    User.create name: params[:name], idade: params[:idade]
    redirect_to action: "lista"
  end

=begin
  def find_user
    @user = User.find(params[:id])
  end
=end

  def show
    #find_user
    @user = User.find(params[:id])
  end

  def edit
    #find_user
    @user = User.find(params[:id])
  end

  def update
    #find_user
    @user = User.find(params[:id])
    @user.update(name: params[:name], idade: params[:idade])
    redirect_to lista_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to lista_path, status: :see_other
  end

end

app/controllers/user_controller_antigo.rb
class UserController < ApplicationController
    attr_accessor :name, :idade
    def lista
      json = Kredis.json "users"
      @users = json.value || []
    end
  
    def cadastro
      integer = Kredis.integer "user_id"
      json = Kredis.json "users"
  
      users = json.value || []
      integer.value = (integer.value || 0) + 1
      params["id"] = integer.value
  
      users << {
        id: params["id"],
        name: params["name"],
        idade: params["idade"]
      }
  
      json.value = users
  
      redirect_to action: "lista" 
    end
  
    def find_user
      @json = Kredis.json "users"
      @especified_user = @json.value.each { |id| @user = id if id["id"] == params["id"].to_i }
    end
  
    def show
      find_user
    end
  
    def edit
      find_user
    end
  
    def update
  
      redirect_to action: "lista"
    end
  
    def destroy
      find_user
      ind = 0 
      users = @json.value
  
      users.each_with_index { |hash, index| ind = index if hash[:id] == params[:id].to_i }
      users.delete_at(ind)
  
      @json.value = users
  
    end
  
  end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/entretenimento/books.html.erb
<div class="row gap-3 pt-5">
  <% @books.each do |book| %>
    <div class="col">
      <div class="card mb-3" style="width: 18rem; height: 14rem;">
        <div class="card-header">
          <h5>
            <%= book[:genre] %>
          </h5>
        </div>
        <div class="card-body">
          <p>
            <%= book[:title] %>
          </p>
        </div>
        <div class="card-footer">
          <p>
            <%= book[:author] %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entretenimento/characters.html.erb
<div class="row gap-3 pt-5">
  <% @characters.each do |character| %>
    <div class="col">
      <div class="card mb-3" style="width: 18rem; height: 8rem;">
        <div class="card-header">
          <h5> Big Bang Theory </h5>
        </div>
        <div class="card-body">
          <p>
            <%= character[:bigbang] %>
          </p>
        </div>
      </div>
      <div class="card mb-3" style="width: 18rem; height: 8rem;">
        <div class="card-header">
          <h5> Supernatural </h5>
        </div>
        <div class="card-body">
          <p>
            <%= character[:supernatural] %>
          </p>
        </div>
      </div>
      <div class="card mb-3" style="width: 18rem; height: 8rem;">
        <div class="card-header">
          <h5> Game of Thrones </h5>
        </div>
        <div class="card-body">
          <p>
            <%= character[:game_of_thrones] %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entretenimento/index.html.erb
<div class="row pt-5">
  <div class="col"></div>
  <div class="col">
    <h5>Info cards on movies, music and on!</h5>
    <p>Take a look in your category of interest and enjoy our content! You can use our cards everyday as recomendations on any topic, as we daily update our database.</p>
  </div>
  <div class="col"></div>
</div>
<div class="row">
  <div class="col"></div>
  <div class="col">
    <%= image_tag "imagecasatorta.jpg", title: "casa torta", widht: "100rem", height: "100rem", class: "rounded mx-auto d-block" %>
  </div>
  <div class="col"></div>
</div>
<div class="row">
  <div class="col"></div>
  <div class="col">
    <h5 class="text-center mb-4">Become a member</h5>
    <%= form_with url: cadastro_path, class: 'text-center' do |form| %>
      <%= text_field_tag :name, nil, placeholder: 'Insert your name here', class: 'form-control mb-3'  %>
      <%= text_field_tag :idade, nil, placeholder: 'Insert your age here', class: 'form-control mb-3' %>
      <%= submit_tag "Submit", class: "btn btn-secondary" %>
    <% end %>
  </div>
  <div class="col"></div>
</div>

app/views/entretenimento/movies.html.erb
<div class="row gap-3 pt-5">
  <% @movies.each do |movie| %>
    <div class="col">
      <div class="card" style="width: 18rem; height: 10rem;">
        <div class="card-header">
          <h5>
            <%= movie[:title] %>
          </h5>
        </div>
        <div class="card-body">
          <p>
            "<%= movie[:quote] %>"
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entretenimento/podcasts.html.erb
<div class="row gap-3 pt-5">
  <% @podcasts.each do |podcast| %>
    <div class="col">
      <div class="card mb-3" style="width: 18rem; height: 14rem;">
        <div class="card-header">
          <h5> Game Podcast </h5>
        </div>
        <div class="card-body">
          <p>
            <%= podcast[:game] %>
          </p>
        </div>
        <div class="card-footer">
          <p>
            <%= podcast[:genre] %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entretenimento/songs.html.erb
<div class="row gap-3 pt-5">
  <% @songs.each do |song| %>
    <div class="col">
      <div class="card" style="width: 18rem; height: 8rem;">
        <div class="card-header">
          <h5>
            <%= song[:genre] %>
          </h5>
        </div>
        <div class="card-body">
          <p>
            <%= song[:band] %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entretenimento/tv_shows.html.erb
<div class="row gap-3 pt-5">
  <% @tv_shows.each do |show| %>
    <div class="col">
      <div class="card mb-3" style="width: 18rem; height: 12rem;">
        <div class="card-header">
          <h5> Sponge Bob </h5>
        </div>
        <div class="card-body">
          <p>
            <%= show[:coisas_estranhas] %>
          </p>
        </div>
      </div>
      <div class="card mb-3" style="width: 18rem; height: 18rem;">
        <div class="card-header">
          <h5> Stranger Things </h5>
        </div>
        <div class="card-body">
          <p>
            <%= show[:bob_esponja] %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entretenimento</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
		<%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

		<%= favicon_link_tag asset_path('am_arctic.jpeg') %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", index_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="<%= podcasts_path %>">Podcasts</a> -->
            <%= link_to "Members", lista_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Recommendations</a>
          <ul class="dropdown-menu">
						<%= link_to "Movies", movies_path, class: "dropdown-item" %>
            <%= link_to "Tv Shows", tv_shows_path, class: "dropdown-item" %>
						<%= link_to "Songs", songs_path, class: "dropdown-item" %>
						<%= link_to "Characters", characters_path, class: "dropdown-item" %>
						<%= link_to "Books", books_path, class: "dropdown-item" %>
						<%= link_to "Podcasts", podcasts_path, class: "dropdown-item" %>
          </ul>
        </li>
        </ul>
      </div>
    </nav>
    <div class="container mb-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user/edit.html.erb
<div class="row pt-5">
  <div class="col"></div>
  <div class="col">
    <h5 class="text-center mb-4">Edit</h5>
    <%= form_with url: update_path, method: :patch, class: 'text-center' do |form| %>
      <%= text_field_tag :name, @user[:name], class: 'form-control mb-3'  %>
      <%= text_field_tag :idade, @user[:idade], class: 'form-control mb-3' %>
      <%= submit_tag "Submit", class: "btn btn-secondary" %>
    <% end %>
  </div>
  <div class="col"></div>
</div>

app/views/user/lista.html.erb
<div class="row gap-3 pt-5">
  <% @users.each do |user| %>
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="https://placekitten.com/640/640" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= user[:name] %></h5>
          <p class="card-text"><%= user[:idade] %> years old.</p>
          <td><%= link_to "show", show_path(id: user[:id]), class: "btn btn-secondary" %></td>
        </div>
      </div>
    </div>
  <% end %>
<div>

app/views/user/show.html.erb
<div class="row pt-5">
  <% if @user.present? %>
    <div class="col">
      <img src="https://placekitten.com/640/640" class="img-thumbnail float-end" width= 50% height= 50% >
    </div>
    <div class="col">
      <h5><%= @user[:name] %></h5>
    </div>
    <div class="col">
      <%= link_to "edit", edit_path(id: @user[:id]), class: "btn btn-warning" %>
      <%= link_to "delete", destroy_path(@user), data: { turbo: true, turbo_method: :delete, turbo_confirm: "Are u sure about deleting it?" }, class: "btn btn-danger" %>
    </div>
  <% end %>  
</div>